src/components/popular/PopularComponent.js, src/styles/popular/popular-component.scss
Reverts pumpumba/Influsion-front-end#21
=> Revert "Fixed twitter icon"

src/components/popular/PopularComponent.js, src/styles/footer/filterFooter.scss, src/styles/footer/subFooter.scss, src/styles/header.scss, src/styles/popular/popular-component.scss, src/styles/popular/popular.scss
- Header sticky
- Footer larger
- overlay with bg
=> Improvements

.cricleci/config.yml
=> configured config file

.babelrc, package.json, src/index.js, src/styles/popular/popular-component.scss, yarn.lock
Reverts pumpumba/Influsion-front-end#48
=> Revert "now preventing user from acceessing app without login"

src/pages/Login.js, src/styles/header.scss, src/styles/login.scss, src/styles/main.scss, src/styles/settings.scss
Also minor font styling in general, made some black fonts grey.
=> Fields for login now have a minimum height.

src/components/admin/AdminFooter.js, src/components/feed/FeedComponent.js, src/index.js, src/pages/AdminBlock.js, src/pages/AdminCreate.js, src/pages/AdminLogin.js, src/pages/AdminPage.js, src/pages/AdminPromote.js, src/pages/AdminSearch.js, src/pages/AdminSettings.js, src/pages/Feed.js, src/styles/admin/admin-footer, src/styles/admin/admin-login.scss, src/styles/admin/admin-page.scss, src/styles/main.scss
the base for team 2 tasks, footer, search etc
=> Admin settings

seleniumMaven/src/test/java/Selenium/FR1to11Test.java
=> Added missing line in FR6

src/pages/Feed.js, src/pages/Search.js
=> fixed typ, issue #120

seleniumMaven/src/test/java/Selenium/FR1to11Test.java
=> Added ready TC in FR23-FR32

src/pages/Login.js
=> resolved issue 128

src/components/register/RegisterAlert.js, src/components/register/RegisterForm.js, src/pages/Register.js, yarn.lock
The styling is fixed but as said maybe we should do automatic log in
=> Fixed styling on button according to issue #127

src/components/popular/PopularComponent.js, src/components/popular/popularSubComponents/PopularComponentClosedView.js, src/components/popular/popularSubComponents/PopularComponentExpandedView.js, src/index.js, src/pages/Popular.js, src/styles/popular/popular-component.scss
=> Instagram video fix

src/components/feed/FeedComponent.js, src/components/popular/PopularComponent.js, src/index.js, src/pages/Popular.js, yarn.lock
Can be merged. Tweets where the text is "" aka empty it will not render
=> Twitter posts that don't have text dont show up in popular anymore

src/components/search/SearchSuggestions.js
#117  calls preventDefault() if you press enter while in the input field instead of reloading page
=> Page does not reload on enter press

src/components/feed/components/FeedComponentMeta.js, src/components/popular/popularSubComponents/PopularComponentExpandedView.js
=> changed number of likes symbol to thumbs up

src/components/feed/FeedComponent.js, src/components/feed/components/FeedComponentHeader.js, src/pages/InfluencerFeed.js
Clicking influencer name while in influencer feed does not link anywhere anymore #93
=> issue #93 fix

src/components/popular/PopularComponent.js
There is no requirement for adding views on influencer.
=> Now we add views on influencers on the following page.

src/components/feed/FeedComponent.js, src/components/feed/components/FeedComponentContent.js, src/components/feed/components/FeedComponentHeader.js, src/components/modifyUser/ModifyForm.js, src/components/popular/PopularComponent.js, src/components/popular/popularSubComponents/PopularComponentClosedView.js, src/components/popular/popularSubComponents/PopularComponentExpandedView.js, src/pages/Feed.js, src/pages/Popular.js
Will add to feed and remove console.logs
=> Ads showing in popular feed

src/components/feed/FeedComponent.js, src/components/feed/components/FeedComponentContent.js, src/styles/feed/components/feed-component-content.scss, src/styles/popular/popular-component.scss
=> Fixed img url in follow feed. And fixed tweet text overflow

src/components/admin/search/Search.js, src/components/search/SearchSuggestions.js, src/pages/Search.js
=> Search info text is hidden when currently searching

src/components/admin/5MostFollowedByAd.js, src/components/admin/PromoteAdInputForm.js, src/pages/AdminPage.js, src/styles/admin/promote-post.scss
Ad_id hardcoded and influencer_image missing.
=> Most followed on ad

src/components/admin/InfluencerListComponent.js, src/components/admin/search/Search.js, src/components/search/SearchSuggestions.js, src/pages/Search.js
Bug fix for bug where placeholder profile image didn't display properly.
=> Placeholder image fix

src/components/modifyUser/ModifyForm.js
=> Fixed for issue133

src/components/admin/5MostFollowedByAd.js
=> When you choose ad_id it fetches the data for that ad.

src/components/admin/5MostFollowedByAd.js, src/components/admin/search/InfluencerFeed.js, src/components/feed/FeedComponent.js, src/components/feed/components/FeedComponentContent.js, src/pages/InfluencerFeed.js
When a user clicks on an ad on following page it is sent to back-end. When a user visits a influencers page it is sent to the back-end.
=> Added clicks on ad on following page, profile visit.

src/components/popular/PopularComponent.js
It will still show video thumbnail as profile image if no user profile image is sent form backend
=> Will change to user profile image on yt posts when it is fixed backend

src/components/admin/CreateAdInputForm.js, src/components/admin/PromoteAdInputForm.js
=> New admin page
